version: "3.1"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    ports:
      - "3002:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
